### ISSUE TITLE
Not a problem, more an advisory about MSTeams.download

### ISSUE THREAD

**Issue by rtrouton** [autopkg/apettinen-recipes#12]
A download link for Microsoft Teams has been posted to http://macadmins.software.

I was able to use it to build a new MicrosoftTeams.download AutoPkg recipe which uses that link: 

https://github.com/autopkg/rtrouton-recipes/blob/master/MicrosoftTeams/MicrosoftTeams.download.recipe

**Comment by apettinen** [comment]
Ach so, thanks for the tip! Cool that you already have a working recipe with that link, that's probably the more future-proof way to go and I'd suggest people to use yours instead.

However, I suggest of keeping mine around still as the custom provider allows downloading non-production and/or non-macOS platforms too. Thus, there's the (slight) possibility that changing my download recipe to direct link might break workflows.

If the provider stops working, we'll kill it then. Or what's your take on this? Tbh, I'm not a fan of multiple recipes for one product and would be happy to kill mine if seen redundant.
