### ISSUE TITLE
Terragrunt.pkg recipe doesn't deliver an executable file

### ISSUE THREAD

**Issue by fishd72** [autopkg/apettinen-recipes#17]
The download from the Terragrunt repository is not set with an executable flag.

I can see the permissions being set on directories within your recipe but this doesn't seem to pass to the file being injected into the package, meaning the resulting file in /usr/local/bin isn't executable.

I'm looking into Jesse Petersons ModeChanger processor to change the permissions on the file, I will submit a PR if I can get it working.

**Comment by fishd72** [comment]
PR submitted

**Comment by apettinen** [comment]
Thanks, merged at [b378de307](https://github.com/autopkg/apettinen-recipes/commit/b378de307dd220fa16d3b632271cfc39cf4baad8)
