### ISSUE TITLE
Brave browser GitHub releases broken; but does (now?) support appcast.xml

### ISSUE THREAD

**Issue by jps3** [autopkg/apettinen-recipes#20]
https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml

I have noted errors lately from AutoPkgr with messages like "Processor: GitHubReleasesInfoProvider: Error: No release assets were found that satisfy the criteria." While I did not got back in versions history of Brave, I do note that at least for v75.0.65.121 on a Mac test box, that it does have an `SUFeedURL` key in its `Info.plist` file pointing to the URL at the top of this message.

If I have a chance later today I will see if I can't submit a pull request. However, I am posting this here if anyone else wants to get on that more quickly.

**Comment by apettinen** [comment]
Hey! Thanks for reporting this. In addition to adding that autoupdate feed, they apparently also deprecated the original repo, and moved to https://github.com/brave/brave-browser - however, this is only for beta, developer, and nightly builds. 
In addition to that feed URL, there's a download link at their homepage, which we can use too.

There's a modified version with the direct download URL here: https://github.com/autopkg/apettinen-recipes/tree/dev/Brave

If desired, I can fix that to use tthe appcast URL.

**Comment by apettinen** [comment]
As #27 I related to this, I decided to finally use the appcast. Thanks for the original tip.

Fixed in https://github.com/autopkg/apettinen-recipes/commit/6a331bd9fcb6d624dda23cc6813c0ce40b884b78
