### ISSUE TITLE
1Password_CLI is now .pkg and not .zip

### ISSUE THREAD

**Issue by tim-fitzgerald** [autopkg/apettinen-recipes#26]
The 1Password_CLI set of recipes are currently broken somewhat - in that they return an out of date version of the tool. This is because when the recipes were written they were matching for .zip downloads, 1PW have changed this to be .pkg for newer releases. 

I have made a PR here:

https://github.com/autopkg/apettinen-recipes/pull/25

**Comment by apettinen** [comment]
Closed, see https://github.com/autopkg/apettinen-recipes/pull/25 for more discussion.
