### ISSUE TITLE
Sparkl feed for Brave, how to verify?

### ISSUE THREAD

**Issue by averell23** [autopkg/apettinen-recipes#28]
How is it possible to verify that "bravesoftware.com" is actually an official domain associated with "brave.com"? The official download appear to all come from "brave.com".

**Comment by apettinen** [comment]
Good question, sorry for a bit late reply! Strictly speaking there is currently no way to (programmatically) verify _any_ domain ownership or association with another domain. However, the `<key>SPARKLE_FEED_URL</key>` value of `<string>https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml</string>` is taken from `Info.plist` inside the Brave.app itself.

There is a bit of discussion in https://github.com/autopkg/apettinen-recipes/issues/27 and https://github.com/autopkg/apettinen-recipes/issues/20 to clarify the decision. 

Furthermore, the actual security check here is codesignature verification, which is performed right after download. If that fails, it should be an alarm of a possible security issue.
