### ISSUE TITLE
Git LFS recipes broken due to upstream changes to macOS release packaging

### ISSUE THREAD

**Issue by ChefAustin** [autopkg/apettinen-recipes#29]
As of v2.12.0 of git-lfs the packaging/release format for git-lfs has changed (See: https://github.com/git-lfs/git-lfs/releases/tag/v2.12.0) and this is causing the AutoPkg recipes to silently fail.

Specifically, the `git-lfs` maintainers have stopped packaging macOS releases as compressed `.tar.gz` archives and, instead, are now packaging them as `.zip` files. The reason for this change is due to Apple not allowing tarballs to be signed/notarized (but `.zip` files are) and more info about this change can be seen in the inciting PR here => https://github.com/git-lfs/git-lfs/pull/4143

As you can see below, the most recent release that the AutoPkg recipe is picking up is the final release of `git-lfs` which was packaged as a tarball (and newer, more recent releases are being ignored):
```
$ autopkg run git-lfs.munki
Processing git-lfs.munki...

The following new items were downloaded:
    Download Path
    -------------
    /Users/Shared/autopkg/Cache/local.munki.git-lfs/downloads/git-lfs-amd64-2.11.0.tar.gz

The following packages were built:
    Identifier          Version  Pkg Path
    ----------          -------  --------
    com.github.git-lfs  2.11.0   /Users/Shared/autopkg/Cache/local.munki.git-lfs/git-lfs-amd64-2.11.0.pkg
```

**Comment by apettinen** [comment]
Ah, I need to fix this asap. Sorry for not noticing this issue before.

**Comment by apettinen** [comment]
Took a bit longer than I anticipated, but this is now fixed in https://github.com/autopkg/apettinen-recipes/commit/f70be540197490f931ffb76a6c7fe4e782725a05 

I also made it possible to change the architecture, in case someone wants to use the download recipe to download e.g. Windows or Linux version.
