### ISSUE TITLE
LuLu now uses DMG file releases

### ISSUE THREAD

**Issue by securitygeneration** [autopkg/apettinen-recipes#31]
https://github.com/autopkg/apettinen-recipes/blob/f70be540197490f931ffb76a6c7fe4e782725a05/LuLu/LuLu.download.recipe#L32

It looks like LuLu now releases DMG files instead of ZIPs: 
https://github.com/objective-see/LuLu/releases/download/v2.2.0/LuLu_2.2.0.dmg

**Comment by apettinen** [comment]
Fixed by https://github.com/autopkg/apettinen-recipes/commit/636cc26086c54048474c2493228ce0b1a7bf02c0
