### ISSUE TITLE
Brave for ARM ?

### ISSUE THREAD

**Issue by adrienlabigne** [autopkg/apettinen-recipes#40]
Hey,

Is you recipe for Brave Apple Silicon ready ?
I means, is there a way to tell it to download arm dmg with detection of Apple Silicon hardware ?

Thanks :)

**Comment by paulgalow** [comment]
FYI: Apparently Brave now distributes a Universal Binary at `https://referrals.brave.com/latest/Brave-Browser.dmg`

**Comment by adrienlabigne** [comment]
Nice ! It is possible to update the recipe with this new URL ?
Thanks in advance

**Comment by adrienlabigne** [comment]
Up ?
