### ISSUE TITLE
MS Teams download is now an installer package

### ISSUE THREAD

**Issue by rtrouton** [autopkg/apettinen-recipes#8]
The MS Teams folks have switched from providing a .dmg with the app inside to now providing an installer package. Latest link from the download page is this:

https://statics.teams.microsoft.com/production-osx/1.1.00.17551/Teams_osx.pkg

May the Teams recipes please be updated to now handle the downloaded installer package?

**Comment by MLBZ521** [comment]
I just submitted PR #9 for this.  👍

**Comment by apettinen** [comment]
Merged. As stated in the merge comment, will update the other recipes soon. Thanks @rtrouton and @MLBZ521 for reporting this - and sorry for a bit slow reply, been busy with the new job. :)

**Comment by rtrouton** [comment]
No worries. I noticed that the updated recipe is still using the old CodeSignatureVerifier values, so I've submitted a new PR https://github.com/autopkg/apettinen-recipes/pull/10 to update that:

**Comment by MLBZ521** [comment]
Whoops, completely missed the CodeSignatureVerifier values.

Thanks guys

**Comment by apettinen** [comment]
Sorry, merged a bit late. Thanks guys! Will be pushing updates to the other recipes today evening.

**Comment by rtrouton** [comment]
All fixed! Thank you.
